/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IFaSolidDiceFive: typeof import('~icons/fa-solid/dice-five')['default']
    IHeroiconsOutlineMenuAlt2: typeof import('~icons/heroicons-outline/menu-alt2')['default']
    'IMdi:diceD12': typeof import('~icons/mdi/dice-d12')['default']
    IMdiLightAlarm: typeof import('~icons/mdi-light/alarm')['default']
    IRiApps2Line: typeof import('~icons/ri/apps2-line')['default']
    ISolar: addCircleLinear\"': typeof import('~icons/solar/add-circle-linear/"')['default']
    'ISolar:addCircleLinear': typeof import('~icons/solar/add-circle-linear')['default']
    'ISolar:addCircleLinear\"': typeof import('~icons/solar/add-circle-linear/"')['default']
    MyCustom: typeof import('./CustomResolved.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
